config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'secret_messages#home'
  get '/secret_messages', to: 'secret_messages#index'
  get '/secret_message/:id', to: 'secret_messages#show', as: :secret_message
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
# frozen_string_literal: true

class Message < ApplicationRecord
  validates :title, :body, presence: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/secret_messages_controller.rb
# frozen_string_literal: true

class SecretMessagesController < ApplicationController
  before_action :authenticate_user!, except: %i[home]

  def home; end

  def index
    @messages = Message.all
  end

  def show
    @message = Message.find(params[:id])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Secreta</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.simplecss.org/simple.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
      <p>Welcome <%= current_user.email %></p>
      <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to 'Login', new_user_session_path %>
      <%= link_to 'Sign up', new_user_registration_path %>
    <% end %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/secret_messages/home.html.erb
<h1>Secret Messages</h1>
<figure>
  <img alt="Image" src="https://i.imgur.com/XZcDi6Q.jpeg" width="83%" height="auto" />
  <figcaption>Source: https://imgur.com/gallery/A3fia</figcaption>
</figure>
<p>Secret messages for your eyes only</p>

app/views/secret_messages/index.html.erb
<h1>Secret Messages</h1>
<% @messages.each do |message| %>
  <h4> <%= link_to message.title, secret_message_path(id: message.id) %> </h4>
<% end %>

app/views/secret_messages/show.html.erb
<h1><%= @message.title %></h1>
<p><%= @message.body %></p>
<%= link_to 'Back', secret_messages_path %>